services:
  vector-db:
    image: qdrant/qdrant
    ports:
     - 6333:6333

  graph-db:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/adminKhusham
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins

volumes:
 neo4j_data:
 neo4j_import:
 neo4j_logs:
 neo4j_plugins: